### ISSUE TITLE
Unexpected death because of TypeError in pickle loads

### ISSUE THREAD

**Issue by patxitalayuela** [stoneworksolutions/redongo#9]
```
INFO:root:Starting Redongo Server..
INFO:root:Loading disk queues...
INFO:root:Loading disk queue took 0.000295877456665
INFO:root:Loading returned disk queue took 0.000118017196655
INFO:root:Running!
INFO:root:Got 2 objects from returned disk queue redongo_disk_queue_returned
ERROR:root:Stopping redongo because unexpected exception: Traceback (most recent call last):
  File "redongo_server.py", line 154, in run
    obj = pickle.loads(orig_obj)
TypeError: must be string, not None

INFO:root:Setting run_stopped to True
INFO:root:Stopping app
INFO:root:Waiting for run_stopped
INFO:root:Returning memory data to Disk Queue
INFO:root:2 objects returned to Disk Queue
INFO:root:Exiting program!
```

**Comment by nsbk** [comment]
More info

```
INFO:root:Starting Redongo Server..
INFO:root:Loading disk queues...
INFO:root:Loading disk queue took 0.000295877456665
INFO:root:Loading returned disk queue took 0.000127077102661
INFO:root:Running!


Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "/opt/redongo/central/env/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
  File "/opt/redongo/central/env/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1201, in mainLoop
    self.runUntilCurrent()
  File "/opt/redongo/central/env/local/lib/python2.7/site-packages/twisted/internet/base.py", line 824, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/opt/redongo/central/env/local/lib/python2.7/site-packages/twisted/internet/task.py", line 218, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "/opt/redongo/central/env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 139, in maybeDeferred
    result = f(*args, **kw)
  File "redongo_server.py", line 341, in check_redis_queue
    if self.redis.llen(self.redisQueue) > self.redisQueueSize or self.disk_queue._length > 0:
  File "/opt/redongo/central/env/local/lib/python2.7/site-packages/redis/client.py", line 1202, in llen
    return self.execute_command('LLEN', name)
  File "/opt/redongo/central/env/local/lib/python2.7/site-packages/redis/client.py", line 570, in execute_command
    connection.send_command(*args)
  File "/opt/redongo/central/env/local/lib/python2.7/site-packages/redis/connection.py", line 556, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/opt/redongo/central/env/local/lib/python2.7/site-packages/redis/connection.py", line 532, in send_packed_command
    self.connect()
  File "/opt/redongo/central/env/local/lib/python2.7/site-packages/redis/connection.py", line 440, in connect
    self.on_connect()
  File "/opt/redongo/central/env/local/lib/python2.7/site-packages/redis/connection.py", line 514, in on_connect
    if nativestr(self.read_response()) != 'OK':
  File "/opt/redongo/central/env/local/lib/python2.7/site-packages/redis/connection.py", line 569, in read_response
    response = self._parser.read_response()
  File "/opt/redongo/central/env/local/lib/python2.7/site-packages/redis/connection.py", line 224, in read_response
    response = self._buffer.readline()
  File "/opt/redongo/central/env/local/lib/python2.7/site-packages/redis/connection.py", line 162, in readline
    self._read_from_socket()
  File "/opt/redongo/central/env/local/lib/python2.7/site-packages/redis/connection.py", line 137, in _read_from_socket
    (e.args,))
redis.exceptions.ConnectionError: Error while reading from socket: ('Connection closed by server.',)


^CINFO:root:Received signal 2
INFO:root:Stopping app
INFO:root:Received signal 2
INFO:root:Stopping app
INFO:root:Waiting for run_stopped
INFO:root:Returning memory data to Disk Queue
INFO:root:0 objects returned to Disk Queue
INFO:root:Exiting program!




^C^C^C^C^C^C^C^C^C^C^C^C^C^C^CKilled
jvizcaino@maou01:central$ sudo /opt/redongo/central/env/bin/python redongo_server.py -r localhost -d 0 -q REDONGO_QUEUE -s 7000000 -P 6385 -p 2000 --log INFO 
INFO:root:Starting Redongo Server..
INFO:root:Loading disk queues...
INFO:root:Loading disk queue took 0.000295877456665
INFO:root:Loading returned disk queue took 0.000118017196655
INFO:root:Running!
INFO:root:Got 2 objects from returned disk queue redongo_disk_queue_returned
ERROR:root:Stopping redongo because unexpected exception: Traceback (most recent call last):
  File "redongo_server.py", line 154, in run
    obj = pickle.loads(orig_obj)
TypeError: must be string, not None

INFO:root:Setting run_stopped to True
INFO:root:Stopping app
INFO:root:Waiting for run_stopped
INFO:root:Returning memory data to Disk Queue
INFO:root:2 objects returned to Disk Queue
INFO:root:Exiting program!
```
